
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jan 14 21:31:47 CET 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 3;
  public static final int INTEGER = 2;
  public static final int NOTEQUAL = 33;
  public static final int GREATER = 34;
  public static final int SEMI = 14;
  public static final int LESS = 30;
  public static final int MINUS = 8;
  public static final int WRITE = 5;
  public static final int AND = 22;
  public static final int LESSEQUAL = 31;
  public static final int INTCONST = 17;
  public static final int OR = 23;
  public static final int BOOL = 26;
  public static final int COMMA = 15;
  public static final int EQUALEQUAL = 32;
  public static final int DOTDOT = 12;
  public static final int DIV = 7;
  public static final int PLUS = 6;
  public static final int ASSIGN = 13;
  public static final int MAIN = 27;
  public static final int ID = 16;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int MUL = 9;
  public static final int GREATEREQUAL = 35;
  public static final int REAL = 21;
  public static final int RIGHTPAR = 11;
  public static final int READ = 4;
  public static final int CHARCONST = 18;
  public static final int WHILE = 24;
  public static final int LEFTPAR = 10;
  public static final int CURLYBRAR = 29;
  public static final int REALCONST = 20;
  public static final int BOOLCONST = 19;
  public static final int CURLYBRAL = 28;
  public static final int DO = 25;
}

